updated pagination
Michaeljogoh/blog-api pull request #1
Opened 2022-06-20 17:59 UTC by Michaeljogoh

updated the blog api

2022-06-20 21:27 UTC, iamr0b0tx requested changes

2022-06-20 21:27 UTC, iamr0b0tx commented on .env
> +
why space

2022-06-21 11:07 UTC, Michaeljogoh commented on .env
> +
Nothing sir , i will fix it

2022-06-21 14:20 UTC, Asylcreek requested changes
You were never supposed to commit your `.env` and `.http` files

2022-06-21 14:20 UTC, Asylcreek commented on controller/blogController.js
> +const patchBlogPost = async (req , res) =>{
You can use `exports.postBlog` to export it, instead of the `module.exports` at the end of the file

2022-06-21 14:20 UTC, Asylcreek commented on model/Blogpost.js
>  const blogPost  = mongoose.model('blogPost', blogPostSchema);
This is supposed to be `BlogPost` by standard naming convention. 

Checkout https://mongoosejs.com/docs/models.html

2022-06-21 14:20 UTC, Asylcreek commented on app.js
> +const blogPost = require("./model/blogPost");
This is supposed to be BlogPost by standard naming convention.

Checkout https://mongoosejs.com/docs/models.html

2022-06-21 14:20 UTC, Asylcreek commented on controller/blogController.js
> +        res.json({addBlogpost});
You need to decide how you want to structure your responses. And you need to be consistent with whatever you are doing ...

You should not send different key names, you can stick to `res.json({data: []})` or just send `res.json(addBlogPost)`

2022-06-21 14:20 UTC, Asylcreek commented on index.js
>  app.use(blogRoutes);
Changing this would also mean that you would need to change the routes in `blogRoutes.js`

2022-06-21 15:48 UTC, Michaeljogoh commented on app.js
> +const pageNumber = (req.query.page == null) ? 1 : request.query.page;
ok sir , i  will fix it.

2022-06-21 15:50 UTC, Michaeljogoh commented on controller/blogController.js
> +    await blogPost.findByIdAndUpdate(req.params.id, {$set: req.body});
It was not updating with only req.params.id but it was updating when i use $set: req.body

2022-06-21 15:50 UTC, Michaeljogoh commented on routes/blogRoutes.js
>  const app = express();
ok i will also update it

2022-06-21 15:51 UTC, Michaeljogoh commented on middleware/errorHandler.js
> +    const statusCode = res.statusCode ? res.statusCode  : 500
ok sir

2022-06-23 13:22 UTC, merged